### ISSUE TITLE
Can end-user check what is being collect and send on their own browser/device ?

### ISSUE THREAD

**Issue by ttpro1995** [mozilla-rally/rally-study-01#107]
Can user check for themselves ? 
How to do so ?

**Comment by rhelmer** [comment]
Hi @ttpro1995, currently the study logs to the console which you can find in `about:debugging` -> "This Firefox" -> "Inspect" on "Mozilla Rally", then clicking on the "Console" tab.

Note that we are considering changing this in https://github.com/mozilla-rally/rally-core-addon/issues/582 but keeping this in some form does make sense to me. @hamilton wdyt?

**Comment by ttpro1995** [comment]
Could we have something more user-friendly ? And more detail ? Like a table, or full json export, ... 

Debugging won''t show everything, data collect in the past.
