### ISSUE TITLE
add short description & icon for study in `manifest.json`

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-study-01#62]
[this line](https://github.com/mozilla-rally/rally-study-01/blob/master/manifest.json#L2) will appear here:

![Screen Shot 2021-03-30 at 10 52 32 AM](https://user-images.githubusercontent.com/95735/113033619-115d5680-9146-11eb-8ca3-a3e19a4806b8.png)

**Comment by magorlick** [comment]
The Add On description is captured [here](https://docs.google.com/document/d/1tPZIEGWeQJFtuGqM9UiLwD4L1TQKJUuHwpO1-6Yr0Mg/edit?usp=sharing).

**Comment by hamilton** [comment]
I drafted #77 to cover both the description & the icon. I'll wait until the upstream blockers on the description are fully resolved and then we can update + merge.
