### ISSUE TITLE
get RS01 a badge

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/rally-study-01#87]

**Comment by rhelmer** [comment]
I'm discussing this with AMO folks in [this slack chat](https://mozilla.slack.com/archives/C4C0HCX6F/p1617826645088500); jorgev suggests that sdevaney could help enable the "by Firefox" badge for this study.

**Comment by rhelmer** [comment]
For future reference, AFAICT the process here is to ask in #addons on slack or to email amo-admins@mozilla.org, they don't seem to use bugs or issues, etc. to track these sorts of requests.

**Comment by rhelmer** [comment]
sdelaney from #addons:
>  I've set Doomscrolling as 'By Firefox' in the AMO admin, so you're free to submit a new version anytime and it will automatically flow into a distinct queue and emerge badged after review.

I'll do a version bump just so we can get this badged.

**Comment by rhelmer** [comment]
> sdelaney from #addons:
> 
> > I've set Doomscrolling as 'By Firefox' in the AMO admin, so you're free to submit a new version anytime and it will automatically flow into a distinct queue and emerge badged after review.
> 
> I'll do a version bump just so we can get this badged.

New release created https://github.com/mozilla-rally/rally-study-01/releases/tag/v0.1.2 and submitted to AMO, I'll close this out once it's approved.

**Comment by hamilton** [comment]
This appears to have been approved.
